runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: www/THEBOYZ.html
  upload: www/THEBOYZ.html

- url: /styles
  static_files: /styles.css
  upload: /styles.css
