runtime: php55

handlers:
- url: /styles.css
  static_dir: styles.css
  
- url: /images/(.*\.(gif|png|jpg))
  static_files: images/\1
  upload: images/(.*\.(gif|png|jpg))
  
- url: /index.html
  script: index.html
